name: Fineract Docker build - MariaDB

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # tag=v3
      - name: Set up JDK 17
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Build the image
        run: ./gradlew :fineract-provider:clean :fineract-provider:jibDockerBuild -x test
      - name: Start the stack
        run: docker-compose up -d
      - name: Wait for stack to come up
        run: sleep 120
      - name: Check health
        run: curl -f -k --retry 5 --retry-connrefused --connect-timeout 30 --retry-delay 30 https://localhost:8443/fineract-provider/actuator/health
      - name: Check info
        run: (( $(curl -f -k --retry 5 --retry-connrefused --connect-timeout 30 --retry-delay 30 https://localhost:8443/fineract-provider/actuator/info | wc --chars) > 100 ))
