ame: Sync Upstream Fineract

env:
  UPSTREAM_URL: "https://github.com/apache/fineract.git"
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UPSTREAM_BRANCH: "develop"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: "develop"
  FETCH_ARGS: ""
  MERGE_ARGS: ""
  PUSH_ARGS: ""
  SPAWN_LOGS: "false"

# This runs every 15min
on:
  schedule:
    - cron: '*/15 * * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync from Fineract Upstream
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}
